### ISSUE TITLE
Crashes when resizing window on ChromeOS

### ISSUE THREAD

**Issue by abendebury** [proninyaroslav/libretorrent#149]
Trying to un-maximize the window results in a crash, with this message:

USER_COMMENT=
ANDROID_VERSION=7.1.1
APP_VERSION_NAME=1.5
BRAND=google
PHONE_MODEL=Google Chromebook Pixel (2015)
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{org.proninyaroslav.libretorrent/org.proninyaroslav.libretorrent.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f090066 (org.proninyaroslav.libretorrent:id/detail_torrent_fragmentContainer) for fragment BlankFragment{41b9ab4 #3 id=0x7f090066}
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2739)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2800)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4603)
at android.app.ActivityThread.-wrap19(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6320)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f090066 (org.proninyaroslav.libretorrent:id/detail_torrent_fragmentContainer) for fragment BlankFragment{41b9ab4 #3 id=0x7f090066}
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:987)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
at android.app.BackStackRecord.run(BackStackRecord.java:816)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
at android.app.FragmentController.execPendingActions(FragmentController.java:371)
at android.app.Activity.performStart(Activity.java:6801)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2703)
... 10 more
java.lang.IllegalArgumentException: No view found for id 0x7f090066 (org.proninyaroslav.libretorrent:id/detail_torrent_fragmentContainer) for fragment BlankFragment{41b9ab4 #3 id=0x7f090066}
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:987)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
at android.app.BackStackRecord.run(BackStackRecord.java:816)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
at android.app.FragmentController.execPendingActions(FragmentController.java:371)
at android.app.Activity.performStart(Activity.java:6801)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2703)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2800)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4603)
at android.app.ActivityThread.-wrap19(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6320)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by PiwwowPants** [comment]
I have no environment where I can test ChromeOS unfortunately. But I am banking on this being an Android 7.x app re-sizing issue that we just don't explicitly support yet.
If you have developer options enabled on your Chromebook, there is an option under "Developer Options > Apps" that is called "Allow free resizing by dragging the border". This should force app re-sizing support and possibly cause the app to not crash.

I have a theory on how to fix this but I'd need to somehow create a ChromeOS test environment first so it could take an undetermined amount of time.

**Comment by proninyaroslav** [comment]
There are many problems with support for chrome os, as its support is not at the official level. Moreover, this is complicated by the absence of the possibility of full-fledged application testing on chrome os.

**Comment by proninyaroslav** [comment]
I checked works in Chrome browser and Chrome OS and it turned out to be very nasty. In addition to non-working dialogs, the background service also doesn't work. Debugging is very hard and I think it's worth waiting for the official support of Android applications.
