### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by e4basil** [proninyaroslav/libretorrent#158]
```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3216184 bytes
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4156)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by proninyaroslav** [comment]
Information in this error is not enough. Can you describe your actions and give a link to the torrent that you downloaded so I can reproduce this error?

**Comment by superbonaci** [comment]
Maybe is related to this?
https://github.com/erickok/transdroid/issues/391
