### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#161]
When Try To Add Torrent Via Magnetic Link . The App Suddenly Crashes

**Comment by proninyaroslav** [comment]
Please don't open issue if you have no information. So please provide version number of LibreTorrent, the magnet link (preferably) and error log.

**Comment by Jithendra-V-Kumar** [comment]
Version 1.6



magnet:?xt=urn:btih:9a3b1cdb33f1781bb6fdf827574e398fdd739474&dn=www.TamilRockers.tw%20-%20Yemaali%20(2018)%5bHDRip%20-%20x264%20-%20400MB%20-%20ESubs%20-%20Tamil%5d.mkv&tr=http%3a%2f%2fmgtracker.org%3a6969%2fannounce&tr=http%3a%2f%2fp4p.arenabg.ch%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2feddie4.nl%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce

**Comment by Jithendra-V-Kumar** [comment]
java.lang.NullPointerException
	at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment$4.run(AddTorrentFragment.java:641)
	at android.app.Activity.runOnUiThread(Activity.java:4662)
	at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment.showFragments(AddTorrentFragment.java:630)
	at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment.access$1100(AddTorrentFragment.java:82)
	at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment$TorrentDecodeTask.onPostExecute(AddTorrentFragment.java:577)
	at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment$TorrentDecodeTask.onPostExecute(AddTorrentFragment.java:476)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by proninyaroslav** [comment]
Did you rotate the screen at this moment?

**Comment by rabbitsmith** [comment]
I get the exact same issue too, v1.6 , as the guy(Tamil guy) who opened this issue. Magnets are not working as expected.

**Comment by rabbitsmith** [comment]
I did not rotate the screen, neither I did not alter any options in the preferences section
