### ISSUE TITLE
Error when adding a torrent via app shortcut

### ISSUE THREAD

**Issue by sanatsathaye** [proninyaroslav/libretorrent#92]
When I try to use the app shortcut the app shows an error saying "Invalid link or path to the torrent". This is the error log:
```
07-18 19:07:12.203 6462-6462/? E/AddTorrentFragment: java.lang.IllegalArgumentException: Can't decode link/path
                                                         at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment.onActivityCreated(AddTorrentFragment.java:260)
                                                         at android.app.Fragment.performActivityCreated(Fragment.java:2362)
                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                                                         at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
                                                         at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
                                                         at android.app.Activity.performCreateCommon(Activity.java:6678)
                                                         at android.app.Activity.performCreate(Activity.java:6686)
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:154)
                                                         at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by proninyaroslav** [comment]
Hello. Fixed in https://github.com/proninyaroslav/libretorrent/commit/8a31d4540c06f539f2259f111ecfa49fdb099736 . Wait for the next release.
